### ISSUE TITLE
Ocelot V11.0.0， AddConfigStoredInConsul Exception

### ISSUE THREAD

**Issue by iexapl** [ThreeMammals/Ocelot.Provider.Consul#4]
## Expected Behavior / New Feature

MissingMethodException: Method not found: 'Void Ocelot.Cache.IOcelotCache`1.AddAndDelete(System.String, !0, System.TimeSpan, System.String)'.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:0.1.1
  - Platform:
  - Subsystem:

**Comment by TomPallister** [comment]
@iexapl when does this happen? On compile? I will take a look ASAP

**Comment by iexapl** [comment]
run

**Comment by TomPallister** [comment]
This is a bug in Ocelot because I have removed the method from the interface in there. Will add it back in and update this package. For now I suggest using Ocelot 9.0.0 only with this package.

**Comment by iexapl** [comment]
The Nuget package must have a dependent Ocelot maximum version number set

**Comment by TomPallister** [comment]
@iexapl this is a bug, the package 11.0.0 should have been OK. I will address the build and release process to avoid this problem again.

**Comment by TomPallister** [comment]
fixed in Ocelot 11.0.2 and Ocelot.Provider.Consul 0.1.2
